### ISSUE TITLE
Mobile View Issues

### ISSUE THREAD

**Issue by reggybudiana** [intanpuspita/RB-Blog-Prototype#1]
Dear Intan, I already change the layout by adding some new background color, adjust width, and change base color. I also change several component like padding, and border set to none in left-side container (the small one). But there are issues when i tried the mobile view through Google Chrome Developer Option, and change mode into **Iphone 5** View Mode, there is something bothering, the vertical scroll at the below of the screen, can you please check that? Thanks

**Comment by intanpuspita** [comment]
Hi @reggybudiana 
I pushed a new code, add media query to solve this issue.
Please kindly pull the latest version, and re-test it.
